version: '3'

services:
  db:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: podbook
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - .database/mysql:/var/lib/mysql
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./back
      target: development
    command: npm run dev
    ports:
      - "3333:3333"
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/back/node_modules/
    env_file:
      - ./back/.env
    depends_on:
      - db
  front:
    image: podbook_front
    container_name: front
    build: ./front
    ports:
      - 8080:80
    depends_on:
      - api